### ISSUE TITLE
coin auto for Fonero ? node-proxy is restarting

### ISSUE THREAD

**Issue by roms2000** [bobbieltd/xmr-node-proxy#3]
If in config file, I add Fonero to mine, proxy is restarting when it receive a hash : 

>  {
>       "hostname": "pool.fonero.hashvault.pro",
>       "port": 3333,
>       "ssl": false,
>       "allowSelfSignedSSL": false,
>       "share": 10,
>       "username": "MYWALLETADDRESS",
>       "password": "x",
>       "keepAlive": true,
>       "coin": "auto",
>       "default": false
>     }
> 

> Log : 
> 1|proxy    | 2018-03-22 00:18 +01:00: Master connected to pool: pool.fonero.hashvault.pro
> 1|proxy    | 2018-03-22 00:18 +01:00: Received new block template from pool.fonero.hashvault.pro
> 1|proxy    | 2018-03-22 00:20 +01:00: Error: Failed to parse block
> 1|proxy    |     at Error (native)
> 1|proxy    |     at BlockTemplate.nextBlob (/home/nodeproxy/xmr-node-proxy-bobbieltd/lib/auto.js:79:19)
> 1|proxy    |     at Miner.getJob (/home/nodeproxy/xmr-node-proxy-bobbieltd/lib/auto.js:120:36)
> 1|proxy    |     at process.slaveMessageHandler (/home/nodeproxy/xmr-node-proxy-bobbieltd/proxy.js:119:50)
> 1|proxy    |     at emitTwo (events.js:111:20)
> 1|proxy    |     at process.emit (events.js:191:7)
> 1|proxy    |     at process.nextTick (internal/child_process.js:744:12)
> 1|proxy    |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
> 1|proxy    |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
> 1|proxy    | 2018-03-22 00:20 +01:00: Error: Failed to parse block
> 1|proxy    |     at Error (native)
> 1|proxy    |     at BlockTemplate.nextBlob (/home/nodeproxy/xmr-node-proxy-bobbieltd/lib/auto.js:79:19)
> 1|proxy    |     at Miner.getJob (/home/nodeproxy/xmr-node-proxy-bobbieltd/lib/auto.js:120:36)
> 1|proxy    |     at process.slaveMessageHandler (/home/nodeproxy/xmr-node-proxy-bobbieltd/proxy.js:119:50)
> 1|proxy    |     at emitTwo (events.js:111:20)
> 1|proxy    |     at process.emit (events.js:191:7)
> 1|proxy    |     at process.nextTick (internal/child_process.js:744:12)
> 1|proxy    |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
> 1|proxy    |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
>

**Comment by bobbieltd** [comment]
Sorry, I was busy and I didn't get notification email for issues. You can use the "coin" : "forknote" for Fonero.

**Comment by bobbieltd** [comment]
There is not auto coin anymore. Coins change their algorithms for anti-ASIC.
