### ISSUE TITLE
error mining ITNS

### ISSUE THREAD

**Issue by rwebb0418** [bobbieltd/xmr-node-proxy#4]
Trying to mine ITNS with the new node proxy.  

- XMR-stak has been set to both cryptonight and intense in the pool config file. 
- Proxy config.json has had the coin set to  XMR, Cryptonight, and forknote

The following error appears in the proxy log:

 itnsproxy > The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN 
 itnsproxy > TypeError: Cannot read property 'activeBlocktemplate' of undefined
 itnsproxy >     at new Miner (/home/nodeproxy/xmr-node-proxy/itnsproxy.js:770:31)
 itnsproxy >     at handleMinerData (/home/nodeproxy/xmr-node-proxy/itnsproxy.js:908:21)
 itnsproxy >     at handleMessage (/home/nodeproxy/xmr-node-proxy/itnsproxy.js:1044:13)
 itnsproxy >     at Socket.<anonymous> (/home/nodeproxy/xmr-node-proxy/itnsproxy.js:1102:25)
 itnsproxy >     at emitOne (events.js:96:13)
 itnsproxy >     at Socket.emit (events.js:188:7)
 itnsproxy >     at readableAddChunk (_stream_readable.js:176:18)
 itnsproxy >     at Socket.Readable.push (_stream_readable.js:134:10)
 itnsproxy >     at TCP.onread (net.js:548:20)
 itnsproxy > Worker 6781 died with code: 1, and signal: null
 itnsproxy > Starting a new worker
 itnsproxy > Worker 6881 is online

And the following error appears in the miner:

 SOCKET ERROR - [stratum+tcp://miner-pc07:5555] RECEIVE error: socket closed

**Comment by rwebb0418** [comment]
Disregard, something must have been typed wrong in my config.json.  Things seem to be working fine now.
