### ISSUE TITLE
Getting error on CryptonightHeavy

### ISSUE THREAD

**Issue by appkoders** [bobbieltd/xmr-node-proxy#6]
```
Received new block template on undefined height from mine.sumo.pool.com
buffer.js:195
    throw new errors.TypeError(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:195:11)
    at new Buffer (buffer.js:170:17)
    at new MasterBlockTemplate (/home/poolproxy/proxy/lib/cryptonightheavy.js:102:19)
    at handleNewBlockTemplate (/home/poolproxy/proxy/proxy.js:719:32)
    at handlePoolMessage (/home/poolproxy/proxy/proxy.js:696:17)
    at Socket.socket.on (/home/poolproxy/proxy/proxy.js:659:17)
    at Socket.emit (events.js:127:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:252:13)
    at Socket.Readable.push (_stream_readable.js:213:10)

```

This is the only thing I changed on my config.json

```
{
      "hostname": "mine.sumo.pool.com",
      "port": 5555,
      "ssl": false,
      "allowSelfSignedSSL": false,
      "share": 100,
      "username": "Sumo<<address>>.proxy",
      "password": "nodeproxy",
      "keepAlive": true,
      "coin": "cryptonightheavy",
      "default": true
    }
```

Also the sumokoin entry on config_example.json uses "cryptonightv7" is that just a typo?

After checking it looks like the pool I am using is not returning the data properly. 
The pool I am using only returns this data
```
{ status: 'OK',
  job:
   { id: '2339878166',
     target: '9bc42000',
     blob: '0303dc9bf0d6057ffb1a3cfea46720615be4f68e920f4dfd700d8d42f899a3eaa80866e7842a0e00000000e033d024909f1ccae04a00e2dcdb313c86243faabfaa6528fb80c7012d46                           ef5a06',
     job_id: '6f7c' },
  id: '2339878166' 
}
```
While your pool returns a lot more

```
{ id: '5df69f86-eaf8-438e-88d7-04c14caba071',
  job:
   { blocktemplate_blob: '0303c19df0d60579edf8eb0d29a0dda9f02b3d11dec040bc20359084c3c14236ade997de144c3e0000000002fbbd0701ffbfbd0701ccc68397880102c88316afc9c0ff482147d2886c331b3230f07792000a73f7a04e11508b50a4d83401ede053fe9c586be35758bef93581b44723b7883347f9d0cd7e01f87ad656ec63021100000000011240000000000000000000000007c320dff7c82d5dccff4c7df6d27f47d06c621da30e93602b41238055529664e40c97f6894ff594358d23079c7f22264c236dbc57720a5e5ab1995cab52abc89142017e7ec07c4d048e49d208ccd868fc917aa02dff1b78c08f05ba96360475c3c47fe08f3599219eeb1d886f0e4af0b4211778c95044e204c487a8f0bf17f2efe416074cf65e222dabf031eea80f6ab3dca142a2c65758251c762eef9d6d27b41b21607e01c44ed74375150a477913589abc6283cb797640299018f9b351e9eec3ea65718cd0a3ec67e2d1ad28571d86cdba75d62952f95e6ec974b510a95948',
     blob_type: 'cryptonote',
     algo: 'cryptonight-heavy',
     variant: 0,
     difficulty: 2011251377,
     height: 122559,
     reserved_offset: 129,
     client_nonce_offset: 141,
     client_pool_offset: 137,
     target_diff: 20000,
     job_id: 'dpMjvDl9clklOpjH/wjbI7UO5D6Z',
     id: '5df69f86-eaf8-438e-88d7-04c14caba071' },
  status: 'OK' }

```

Does this proxy works on your pools only?

**Comment by appkoders** [comment]
It looks like the proxy only works on pools using Snipa22's nodejs-pool only.
