### ISSUE TITLE
Received new block template on undefined height from

### ISSUE THREAD

**Issue by alebeta90** [bobbieltd/xmr-node-proxy#7]
Hi @bobbieltd ,

I was setting up the xmr node proxy for superiorcoin pool, but i get the next message:

Xmr-Node-Proxy (XNP) v0.1.1
Cluster master setting up 8 workers...
Activating Web API server on 0.0.0.0:8080
Worker 30056 is online
Worker 30061 is online
Worker 30062 is online
Worker 30068 is online
Worker 30075 is online
Worker 30086 is online
Worker 30092 is online
Worker 30093 is online
Master connected to pool: pool01.supercoin.minando.com
Received new block template on undefined height from pool01.supercoin.minandoando.com
buffer.js:183
    throw new TypeError(kFromErrorMsg);
    ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at new MasterBlockTemplate (/home/user/xmr-node-proxy/lib/cryptonightv7.js:102:19)
    at handleNewBlockTemplate (/home/user/xmr-node-proxy/proxy.js:723:32)
    at handlePoolMessage (/home/user/xmr-node-proxy/proxy.js:700:17)
    at Socket.socket.on (/home/user/xmr-node-proxy/proxy.js:663:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)

-------------
I think the message is clear about the undefined height of the block, the only thing I want to know is if it is at proxy side or pool side. Then If you can give me a hint I can solve it,

Thanks and all the best

**Comment by bobbieltd** [comment]
1. Typo error : superiorcoin , not supercoin
2. cryptonote-pool , not nodejs-pool

**Comment by alebeta90** [comment]
Hi,

It is not a typo. It is the real FQDN of the pool. 

Cryptonote pool works with Nodejs, isn't?

Thanks for your help.
All the best

**Comment by bobbieltd** [comment]
xmr-node-proxy only works with pools that are made from Snipa's nodejs-pool (not pools that are made from node.js).
So not all pools will work with proxy. Check the footer of the pool website.
